export {
  MAX_COMMAND_VALIDATION_ISSUES,
  dispatchDocumentCommand,
  type DocumentCommandError,
  type DocumentCommandFailureCode,
  type DocumentCommandResult,
} from './commands/dispatcher';
export {
  AssetCommandSchema,
  BoardCommandSchema,
  CreateAssetCommandSchema,
  CreateAlternateCommandSchema,
  CreateBoardCommandSchema,
  CreateElementCommandSchema,
  DOCUMENT_COMMAND_TYPES,
  DeleteBoardCommandSchema,
  DeleteAssetCommandSchema,
  DeleteAlternateCommandSchema,
  DeleteElementCommandSchema,
  DocumentCommandSchema,
  ElementCommandSchema,
  GroupElementsCommandSchema,
  RestoreBoardCommandSchema,
  RenameBoardCommandSchema,
  ReorderBoardCommandSchema,
  ReorderElementCommandSchema,
  ReorderElementSiblingsCommandSchema,
  SetBoardNoteCommandSchema,
  SelectBoardVersionCommandSchema,
  SetElementFrameCommandSchema,
  SetElementAssetsCommandSchema,
  SetElementLinkCommandSchema,
  SetElementLockedCommandSchema,
  SetElementPropertiesCommandSchema,
  UngroupElementCommandSchema,
  TrashBoardCommandSchema,
  type AssetCommand,
  type BoardCommand,
  type CreateAssetCommand,
  type CreateAlternateCommand,
  type CreateBoardCommand,
  type CreateElementCommand,
  type DeleteAssetCommand,
  type DeleteBoardCommand,
  type DeleteAlternateCommand,
  type DeleteElementCommand,
  type DocumentCommand,
  type ElementCommand,
  type GroupElementsCommand,
  type RestoreBoardCommand,
  type RenameBoardCommand,
  type ReorderBoardCommand,
  type ReorderElementCommand,
  type ReorderElementSiblingsCommand,
  type SetBoardNoteCommand,
  type SelectBoardVersionCommand,
  type SetElementFrameCommand,
  type SetElementAssetsCommand,
  type SetElementLinkCommand,
  type SetElementLockedCommand,
  type SetElementPropertiesCommand,
  type UngroupElementCommand,
  type TrashBoardCommand,
} from './commands/schema';
export {
  containsControlHitPoint,
  getControlAccessibleName,
  getControlHitSegments,
  getControlHitShapePadding,
  type ControlHitBounds,
  type ControlHitPoint,
  type ControlHitSegment,
} from './controls/control-hit-shape';
export {
  migrateControlProperties,
  migrateProjectControlProperties,
  type ControlDefinitionResolver,
  type ControlPropertiesMigrationResult,
  type ControlPropertyMigrationError,
  type ControlPropertyMigrationErrorCode,
  type ProjectControlMigrationResult,
} from './controls/control-property-migration';
export {
  CUSTOM_ICON_REFERENCE_PREFIX,
  CustomIconReferenceSchema,
  createCustomIconReference,
  parseCustomIconReference,
} from './controls/custom-icon-reference';
export {
  assertControlDefinitionsConform,
  type ControlAccessibilityDefinition,
  type ControlAccessibilityRole,
  type ControlAutoSizeAxis,
  type ControlAutoSizeInsets,
  type ControlAutoSizePolicy,
  type ControlCapabilities,
  type ControlCategory,
  type ControlDefinition,
  type ControlExportDefinition,
  type ControlGroupingCapability,
  type ControlHitShape,
  type ControlHitShapePoint,
  type ControlInspectorChoiceOption,
  type ControlInspectorPropertyField,
  type ControlInspectorSection,
  type ControlPropertyMigration,
  type ControlResizeAxes,
  type ControlPaletteMetadata,
  type ControlSceneDefinition,
  type ControlSize,
  type ControlTextCapability,
  type ControlThumbnailDefinition,
  type ControlVisualKind,
} from './controls/control-definition';
export {
  CONTROL_TYPES,
  FOUNDATION_CONTROL_TYPES,
  getControlSpec,
  getControlSpecByDrawShortcut,
  listPaletteControlSpecs,
  listControlSpecs,
} from './controls/control-spec';
export {
  AssetIdSchema,
  BoardIdSchema,
  ElementIdSchema,
  ProjectIdSchema,
  type AssetId,
  type BoardId,
  type ElementId,
  type ProjectId,
} from './document/ids';
export { createEmptyProjectDocument, type EmptyProjectDocumentInput } from './document/factory';
export {
  migrateProjectDocumentV1ToV2,
  migrateProjectDocumentV2ToV3,
  migrateProjectDocumentV3ToV4,
  type ProjectDocumentMigrationResult,
} from './document/migrations';
export { ElementOwnerSchema, type ElementOwner } from './document/owner';
export {
  createElementLocationIndex,
  selectBoardElementIds,
  selectBoardPresentationId,
  selectBoardCommandAvailability,
  selectBoardRootElements,
  selectElementCommandAvailability,
  selectElementLockState,
  selectElementLocation,
  selectElementWorldBounds,
  selectOrderedBoards,
  selectOrderedChildren,
  selectOwnerChildIds,
  selectSelectionWorldBounds,
  type BoardCommandAvailability,
  type ElementCommandAvailability,
  type ElementLocation,
  type ElementLocationIndex,
  type ElementLockState,
} from './document/selectors';
export {
  AssetReferenceSchema,
  BoardNoteSchema,
  BoardSchema,
  ControlTypeIdSchema,
  DocumentTitleSchema,
  ElementLinkSchema,
  ElementNodeSchema,
  ElementPropertiesSchema,
  JsonValueSchema,
  PROJECT_DOCUMENT_SCHEMA_VERSION,
  ProjectDocumentShapeSchema,
  WorldRectSchema,
  type AssetReference,
  type Board,
  type BoardNote,
  type ControlTypeId,
  type ElementLink,
  type ElementNode,
  type ElementProperties,
  type JsonValue,
  type ProjectDocumentShape,
  type WorldRect,
} from './document/schema';
export { ProjectDocumentV1ShapeSchema } from './document/schema-v1';
export { ProjectDocumentV2ShapeSchema, type ProjectDocumentV2Shape } from './document/schema-v2';
export { ProjectDocumentV3ShapeSchema, type ProjectDocumentV3Shape } from './document/schema-v3';
export {
  MAX_DOCUMENT_VALIDATION_ISSUES,
  ProjectDocumentSchema,
  parseProjectDocument,
  type DocumentValidationIssue,
  type ProjectDocument,
  type ProjectDocumentParseResult,
} from './document/validation';
export {
  DEFAULT_HISTORY_LIMIT,
  MAX_HISTORY_LIMIT,
  MAX_HISTORY_TRANSACTION_COMMANDS,
  canRedoDocumentHistory,
  canUndoDocumentHistory,
  createDocumentHistory,
  createHistorySaveTokenId,
  createHistoryStateId,
  isDocumentHistoryDirty,
  selectRedoLabel,
  selectUndoLabel,
  type CreateDocumentHistoryOptions,
  type DocumentHistoryState,
  type HistoryEntry,
  type HistoryOperationError,
  type HistoryOperationErrorCode,
  type HistoryOperationResult,
  type HistoryStateId,
  type HistoryTransactionOptions,
} from './history/model';
export {
  dispatchHistoryCommand,
  dispatchHistoryTransaction,
  redoDocumentHistory,
  undoDocumentHistory,
} from './history/operations';
export {
  beginDocumentHistorySave,
  completeDocumentHistorySave,
  failDocumentHistorySave,
  type BeginHistorySaveResult,
  type HistorySaveError,
  type HistorySaveErrorCode,
  type HistorySaveSnapshot,
  type ResolveHistorySaveResult,
} from './history/save-state';
