export const DESIGN_TOKENS = {
  color: {
    ink: '#202428',
    mutedInk: '#67717A',
    chrome: '#F3F4F5',
    panel: '#E4E6E8',
    divider: '#C8CDD2',
    canvas: '#FFFFFF',
    accent: '#2E9DDF',
    accentStrong: '#167DB9',
    danger: '#B63831',
  },
  font: {
    ui: '"IBM Plex Sans", sans-serif',
    wireframe: '"Comic Neue", cursive',
    captionSize: 11,
    bodySize: 13,
    titleSize: 14,
    lineHeight: 1.4,
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
  },
  radius: {
    compact: 6,
    panel: 8,
  },
  shell: {
    initialWindowWidth: 1440,
    initialWindowHeight: 900,
    commandBarHeight: 40,
    statusBarHeight: 24,
    categoryBarHeight: 32,
    controlShelfHeight: 84,
    navigatorWidth: 224,
    inspectorWidth: 320,
    minWindowWidth: 1024,
    minWindowHeight: 680,
    canvasEmptyWidth: 456,
    canvasCopyWidth: 384,
  },
  control: {
    height: 24,
    borderWidth: 1,
    iconSize: 16,
    iconStrokeWidth: 1.4,
  },
  motion: {
    fast: 80,
    standard: 140,
    reduced: 0.01,
  },
  layer: {
    shell: 1,
    overlay: 100,
  },
} as const;

const px = (value: number): string => `${String(value)}px`;

/**
 * Renderer CSS variables are generated from the same values used by native
 * window setup. This prevents platform chrome and renderer chrome from
 * carrying separate copies of shell geometry or startup colors.
 */
export const DESIGN_TOKEN_CSS_VARIABLES = {
  '--color-ink': DESIGN_TOKENS.color.ink,
  '--color-muted-ink': DESIGN_TOKENS.color.mutedInk,
  '--color-chrome': DESIGN_TOKENS.color.chrome,
  '--color-panel': DESIGN_TOKENS.color.panel,
  '--color-divider': DESIGN_TOKENS.color.divider,
  '--color-canvas': DESIGN_TOKENS.color.canvas,
  '--color-accent': DESIGN_TOKENS.color.accent,
  '--color-accent-strong': DESIGN_TOKENS.color.accentStrong,
  '--color-danger': DESIGN_TOKENS.color.danger,
  '--font-ui': DESIGN_TOKENS.font.ui,
  '--font-wireframe': DESIGN_TOKENS.font.wireframe,
  '--font-size-caption': px(DESIGN_TOKENS.font.captionSize),
  '--font-size-body': px(DESIGN_TOKENS.font.bodySize),
  '--font-size-title': px(DESIGN_TOKENS.font.titleSize),
  '--line-height': String(DESIGN_TOKENS.font.lineHeight),
  '--space-1': px(DESIGN_TOKENS.space[1]),
  '--space-2': px(DESIGN_TOKENS.space[2]),
  '--space-3': px(DESIGN_TOKENS.space[3]),
  '--space-4': px(DESIGN_TOKENS.space[4]),
  '--space-5': px(DESIGN_TOKENS.space[5]),
  '--space-6': px(DESIGN_TOKENS.space[6]),
  '--radius-compact': px(DESIGN_TOKENS.radius.compact),
  '--radius-panel': px(DESIGN_TOKENS.radius.panel),
  '--command-bar-height': px(DESIGN_TOKENS.shell.commandBarHeight),
  '--status-bar-height': px(DESIGN_TOKENS.shell.statusBarHeight),
  '--category-bar-height': px(DESIGN_TOKENS.shell.categoryBarHeight),
  '--control-shelf-height': px(DESIGN_TOKENS.shell.controlShelfHeight),
  '--navigator-width': px(DESIGN_TOKENS.shell.navigatorWidth),
  '--inspector-width': px(DESIGN_TOKENS.shell.inspectorWidth),
  '--shell-min-width': px(DESIGN_TOKENS.shell.minWindowWidth),
  '--shell-min-height': px(DESIGN_TOKENS.shell.minWindowHeight),
  '--canvas-empty-width': px(DESIGN_TOKENS.shell.canvasEmptyWidth),
  '--canvas-copy-width': px(DESIGN_TOKENS.shell.canvasCopyWidth),
  '--control-height': px(DESIGN_TOKENS.control.height),
  '--border-width': px(DESIGN_TOKENS.control.borderWidth),
  '--icon-size': px(DESIGN_TOKENS.control.iconSize),
  '--icon-stroke-width': String(DESIGN_TOKENS.control.iconStrokeWidth),
  '--motion-fast': `${String(DESIGN_TOKENS.motion.fast)}ms`,
  '--motion-standard': `${String(DESIGN_TOKENS.motion.standard)}ms`,
  '--motion-reduced': `${String(DESIGN_TOKENS.motion.reduced)}ms`,
  '--layer-shell': String(DESIGN_TOKENS.layer.shell),
  '--layer-overlay': String(DESIGN_TOKENS.layer.overlay),
} as const satisfies Record<`--${string}`, string>;
