const FONT_FAMILIES = Object.freeze({
  ui: 'IBM Plex Sans',
  wireframe: 'Comic Neue',
});

export const DESIGN_TOKENS = {
  color: {
    ink: '#202428',
    mutedInk: '#67717A',
    chrome: '#F3F4F5',
    panel: '#E4E6E8',
    panelStrong: '#D1D5D8',
    divider: '#C8CDD2',
    controlBorder: '#87919A',
    canvas: '#FFFFFF',
    canvasGrid: '#DDE1E4',
    placeholder: '#DDE0E3',
    accent: '#2D9CDE',
    accentStrong: '#157AB5',
    guide: '#E04B4B',
    danger: '#B63831',
    warning: '#8A5D00',
    success: '#2D7A4C',
    onDarkStrong: 'rgba(255, 255, 255, 0.88)',
    onDark: '#FFFFFF',
    onDarkMuted: 'rgba(255, 255, 255, 0.62)',
    onDarkSubtle: 'rgba(255, 255, 255, 0.54)',
    onDarkDisabled: 'rgba(255, 255, 255, 0.48)',
    onDarkFaint: 'rgba(255, 255, 255, 0.50)',
    darkSurface: 'rgba(255, 255, 255, 0.09)',
    darkDivider: 'rgba(255, 255, 255, 0.14)',
    darkDividerStrong: 'rgba(255, 255, 255, 0.16)',
    scrim: 'rgba(32, 36, 40, 0.48)',
    shadow: 'rgba(32, 36, 40, 0.12)',
  },
  font: {
    family: FONT_FAMILIES,
    ui: `"${FONT_FAMILIES.ui}", sans-serif`,
    wireframe: `"${FONT_FAMILIES.wireframe}", cursive`,
    captionSize: 11,
    bodySize: 13,
    titleSize: 14,
    lineHeight: 1.4,
    displayLineHeight: 1.15,
    tracking: {
      compact: '0.01em',
      label: '0.04em',
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
    },
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
  },
  radius: {
    compact: 6,
    panel: 8,
  },
  shell: {
    initialWindowWidth: 1440,
    initialWindowHeight: 900,
    commandBarHeight: 40,
    statusBarHeight: 24,
    categoryBarHeight: 32,
    controlShelfHeight: 84,
    navigatorWidth: 224,
    navigatorMinWidth: 180,
    navigatorMaxWidth: 360,
    collapsedPaneWidth: 32,
    inspectorWidth: 320,
    inspectorMinWidth: 288,
    inspectorMaxWidth: 420,
    minWindowWidth: 1024,
    minWindowHeight: 680,
    minViewportWidth: 960,
    minViewportHeight: 600,
    canvasEmptyWidth: 456,
    canvasCopyWidth: 384,
    modalWidth: 560,
    noticeWidth: 360,
    popoverWidth: 288,
    tooltipWidth: 240,
  },
  control: {
    height: 24,
    borderWidth: 1,
    iconSize: 16,
    iconStrokeWidth: 1.4,
    sliderThumbSize: 12,
    sliderTrackSize: 4,
    swatchWidth: 64,
  },
  editor: {
    selectionHandleHitSize: 16,
    selectionHandleSize: 8,
  },
  motion: {
    fast: 80,
    standard: 140,
    reduced: 0.01,
  },
  opacity: {
    disabled: 0.48,
    enabled: 1,
    muted: 0.76,
    selectionFill: 0.12,
  },
  shadow: {
    floatingBlur: 36,
    floatingOffsetY: 12,
  },
  layer: {
    localRaised: 1,
    shell: 1,
    canvasOverlay: 10,
    overlay: 100,
    popover: 200,
    toast: 300,
    modal: 400,
  },
} as const;

const px = (value: number): string => `${String(value)}px`;

/**
 * Renderer CSS variables are generated from the same values used by native
 * window setup. This prevents platform chrome and renderer chrome from
 * carrying separate copies of shell geometry or startup colors.
 */
export const DESIGN_TOKEN_CSS_VARIABLES = {
  '--color-ink': DESIGN_TOKENS.color.ink,
  '--color-muted-ink': DESIGN_TOKENS.color.mutedInk,
  '--color-chrome': DESIGN_TOKENS.color.chrome,
  '--color-panel': DESIGN_TOKENS.color.panel,
  '--color-panel-strong': DESIGN_TOKENS.color.panelStrong,
  '--color-divider': DESIGN_TOKENS.color.divider,
  '--color-control-border': DESIGN_TOKENS.color.controlBorder,
  '--color-canvas': DESIGN_TOKENS.color.canvas,
  '--color-canvas-grid': DESIGN_TOKENS.color.canvasGrid,
  '--color-placeholder': DESIGN_TOKENS.color.placeholder,
  '--color-accent': DESIGN_TOKENS.color.accent,
  '--color-accent-strong': DESIGN_TOKENS.color.accentStrong,
  '--color-guide': DESIGN_TOKENS.color.guide,
  '--color-danger': DESIGN_TOKENS.color.danger,
  '--color-warning': DESIGN_TOKENS.color.warning,
  '--color-success': DESIGN_TOKENS.color.success,
  '--color-on-dark-strong': DESIGN_TOKENS.color.onDarkStrong,
  '--color-on-dark': DESIGN_TOKENS.color.onDark,
  '--color-on-dark-muted': DESIGN_TOKENS.color.onDarkMuted,
  '--color-on-dark-subtle': DESIGN_TOKENS.color.onDarkSubtle,
  '--color-on-dark-disabled': DESIGN_TOKENS.color.onDarkDisabled,
  '--color-on-dark-faint': DESIGN_TOKENS.color.onDarkFaint,
  '--color-dark-surface': DESIGN_TOKENS.color.darkSurface,
  '--color-dark-divider': DESIGN_TOKENS.color.darkDivider,
  '--color-dark-divider-strong': DESIGN_TOKENS.color.darkDividerStrong,
  '--color-scrim': DESIGN_TOKENS.color.scrim,
  '--color-shadow': DESIGN_TOKENS.color.shadow,
  '--font-ui': DESIGN_TOKENS.font.ui,
  '--font-wireframe': DESIGN_TOKENS.font.wireframe,
  '--font-size-caption': px(DESIGN_TOKENS.font.captionSize),
  '--font-size-body': px(DESIGN_TOKENS.font.bodySize),
  '--font-size-title': px(DESIGN_TOKENS.font.titleSize),
  '--line-height': String(DESIGN_TOKENS.font.lineHeight),
  '--display-line-height': String(DESIGN_TOKENS.font.displayLineHeight),
  '--font-weight-regular': String(DESIGN_TOKENS.font.weight.regular),
  '--font-weight-medium': String(DESIGN_TOKENS.font.weight.medium),
  '--font-weight-semibold': String(DESIGN_TOKENS.font.weight.semibold),
  '--font-tracking-compact': DESIGN_TOKENS.font.tracking.compact,
  '--font-tracking-label': DESIGN_TOKENS.font.tracking.label,
  '--space-1': px(DESIGN_TOKENS.space[1]),
  '--space-2': px(DESIGN_TOKENS.space[2]),
  '--space-3': px(DESIGN_TOKENS.space[3]),
  '--space-4': px(DESIGN_TOKENS.space[4]),
  '--space-5': px(DESIGN_TOKENS.space[5]),
  '--space-6': px(DESIGN_TOKENS.space[6]),
  '--radius-compact': px(DESIGN_TOKENS.radius.compact),
  '--radius-panel': px(DESIGN_TOKENS.radius.panel),
  '--command-bar-height': px(DESIGN_TOKENS.shell.commandBarHeight),
  '--status-bar-height': px(DESIGN_TOKENS.shell.statusBarHeight),
  '--category-bar-height': px(DESIGN_TOKENS.shell.categoryBarHeight),
  '--control-shelf-height': px(DESIGN_TOKENS.shell.controlShelfHeight),
  '--navigator-width': px(DESIGN_TOKENS.shell.navigatorWidth),
  '--navigator-min-width': px(DESIGN_TOKENS.shell.navigatorMinWidth),
  '--navigator-max-width': px(DESIGN_TOKENS.shell.navigatorMaxWidth),
  '--collapsed-pane-width': px(DESIGN_TOKENS.shell.collapsedPaneWidth),
  '--inspector-width': px(DESIGN_TOKENS.shell.inspectorWidth),
  '--inspector-min-width': px(DESIGN_TOKENS.shell.inspectorMinWidth),
  '--inspector-max-width': px(DESIGN_TOKENS.shell.inspectorMaxWidth),
  '--canvas-empty-width': px(DESIGN_TOKENS.shell.canvasEmptyWidth),
  '--canvas-copy-width': px(DESIGN_TOKENS.shell.canvasCopyWidth),
  '--modal-width': px(DESIGN_TOKENS.shell.modalWidth),
  '--notice-width': px(DESIGN_TOKENS.shell.noticeWidth),
  '--popover-width': px(DESIGN_TOKENS.shell.popoverWidth),
  '--tooltip-width': px(DESIGN_TOKENS.shell.tooltipWidth),
  '--control-height': px(DESIGN_TOKENS.control.height),
  '--border-width': px(DESIGN_TOKENS.control.borderWidth),
  '--icon-size': px(DESIGN_TOKENS.control.iconSize),
  '--icon-stroke-width': String(DESIGN_TOKENS.control.iconStrokeWidth),
  '--slider-thumb-size': px(DESIGN_TOKENS.control.sliderThumbSize),
  '--slider-track-size': px(DESIGN_TOKENS.control.sliderTrackSize),
  '--swatch-width': px(DESIGN_TOKENS.control.swatchWidth),
  '--selection-handle-hit-size': px(DESIGN_TOKENS.editor.selectionHandleHitSize),
  '--selection-handle-size': px(DESIGN_TOKENS.editor.selectionHandleSize),
  '--motion-fast': `${String(DESIGN_TOKENS.motion.fast)}ms`,
  '--motion-standard': `${String(DESIGN_TOKENS.motion.standard)}ms`,
  '--motion-reduced': `${String(DESIGN_TOKENS.motion.reduced)}ms`,
  '--opacity-disabled': String(DESIGN_TOKENS.opacity.disabled),
  '--opacity-enabled': String(DESIGN_TOKENS.opacity.enabled),
  '--opacity-muted': String(DESIGN_TOKENS.opacity.muted),
  '--opacity-selection-fill': String(DESIGN_TOKENS.opacity.selectionFill),
  '--shadow-floating': `0 ${px(DESIGN_TOKENS.shadow.floatingOffsetY)} ${px(DESIGN_TOKENS.shadow.floatingBlur)} var(--color-shadow)`,
  '--layer-local-raised': String(DESIGN_TOKENS.layer.localRaised),
  '--layer-shell': String(DESIGN_TOKENS.layer.shell),
  '--layer-canvas-overlay': String(DESIGN_TOKENS.layer.canvasOverlay),
  '--layer-overlay': String(DESIGN_TOKENS.layer.overlay),
  '--layer-popover': String(DESIGN_TOKENS.layer.popover),
  '--layer-toast': String(DESIGN_TOKENS.layer.toast),
  '--layer-modal': String(DESIGN_TOKENS.layer.modal),
} as const satisfies Record<`--${string}`, string>;
